### ISSUE TITLE
Possible rename?

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/DimensionalArrayTraits.jl#1]
Thank you guys for the initiative! Looking forward to contribute.

What do you think of renaming the package to `DimensionalArrays.jl` only? The traits are "implicit" at least this is the convention in other packages like Tables.jl, StatsModels.jl, etc.

**Comment by rafaqz** [comment]
This package is to hold grid traits like regularity/irregularity, coord location (start/center) and other things that can be used for handling arrays. 

I wouldn't actually define array types itself, and most packages that end with `Arrays` define an array type.

**Comment by juliohm** [comment]
It makes sense

**Comment by juliohm** [comment]
Closing the issue.
