### ISSUE TITLE
Brainstorming spatial data/domain requirements

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/DimensionalArrayTraits.jl#2]
Copying/pasting the requirements from our Google Docs to here:

- Return coordinates lon/lat/depth/time (and arbitrary dimension) for a given index i,j,k,...
- Tell what each coordinate represent (is the 3rd dimension time or depth or something else?).
- Maybe re-use the CF convention names (longitude, latitude, time, …)
- Subsetting based on lon/lat/depth/time (and arbitrary dimension) bounding box (how to handle irregular grid?)
- Find the k nearest points for a given location
- Integral over a raster (knowing the “volume” of each grid cell)
- Time: is the value for the start, middle or (probably never) the end of the duration. Is it an average of the whole period or a specific point in the cell. These specifications should also generalise to any other dimension type.
- Categorical dimensions with no size or regularity
- Arrays can be plotted correctly using the grid information
- Use cf conventions where applicable
- For me units and other metadata can be out-of-scope, at least for now)
- Zero cost indexing (only works on regular grids?)
- Lazy affine transformations on the data

**Comment by Alexander-Barth** [comment]
It is a bit difficult to add or revise a requirement list with a Github issue. Would you agree to put this list in the README.md file (or elsewhere) so that one can modify it more easily?

**Comment by juliohm** [comment]
Good idea. Please feel free to move it to the readme.

**Comment by Alexander-Barth** [comment]
OK, I put it in the README.mk with some propositions about possible interfaces. Fell free to add other ideas so that we can select to most suitable.
